# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2l3aiETB0eUsJYYy8_bTFKRg7kjYPZe
"""

import random

#Biased hiring algorithm

Employees = [{'name':'sumaya','gender':'M','Age':25},{'name':'jabo','gender':'F','Age':25},{'name':'mutesi','gender':'F','Age':25}]

def biased_hire(employees):


  return [employee for employee in employees if employee['Age'] == 25]

print("biased hiring:",biased_hire(Employees))

def fiar_hire(employees):
    return random.choice(employees)
print("fair_hiring:",fiar_hire(Employees) )

